version: 2
orbs:
  cypress: cypress-io/cypress@1.1.0
  workflows:
    build:
      jobs:
        - checkout
        - run: npm install
        - run: npm test
        - cypress/run:
            parallel: true
            parallelism: 4
