version: 2
jobs:
  build: 
    working_directory: ~/temp
    docker: 
      - image: cypress/base:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run cy:run  
